/*
 * uart.h
 *
 * Created: 30/12/2014 23:05:44
 *  Author: speirano
 */ 


#ifndef SME_UART_H_
#define SME_UART_H_

#define CONF_STDIO_USART          EDBG_CDC_MODULE
#define CONF_STDIO_MUX_SETTING    EDBG_CDC_SERCOM_MUX_SETTING
#define CONF_STDIO_PINMUX_PAD0    EDBG_CDC_SERCOM_PINMUX_PAD0
#define CONF_STDIO_PINMUX_PAD1    EDBG_CDC_SERCOM_PINMUX_PAD1
#define CONF_STDIO_PINMUX_PAD2    EDBG_CDC_SERCOM_PINMUX_PAD2
#define CONF_STDIO_PINMUX_PAD3    EDBG_CDC_SERCOM_PINMUX_PAD3
#define CONF_STDIO_BAUDRATE       38400

/* RX USART to test */
#define CONF_RX_USART              EXT1_UART_MODULE
#define CONF_RX_USART_SERCOM_MUX   EXT1_UART_SERCOM_MUX_SETTING
#define CONF_RX_USART_PINMUX_PAD0  EXT1_UART_SERCOM_PINMUX_PAD0
#define CONF_RX_USART_PINMUX_PAD1  EXT1_UART_SERCOM_PINMUX_PAD1
#define CONF_RX_USART_PINMUX_PAD2  EXT1_UART_SERCOM_PINMUX_PAD2
#define CONF_RX_USART_PINMUX_PAD3  EXT1_UART_SERCOM_PINMUX_PAD3

/* TX USART to test
 *
 * There is only one SERCOM for USART on the EXT headers of the rev. 2
 * SAM D21 Xplained Pro. The settings below are a hack to get a second
 * USART via a SERCOM that is not mapped to a RX/TX pin on a header.
 *
 * More specifically, it is the SPI SERCOM on EXT1, with RX mapped to PA05
 * (EXT1_PIN_15 or "SS_0") and TX mapped to PA04 (EXT1_PIN_17 or "MISO").
 */
#define CONF_TX_USART              SERCOM0
#define CONF_TX_USART_SERCOM_MUX   USART_RX_1_TX_0_XCK_1
#define CONF_TX_USART_PINMUX_PAD0  PINMUX_PA04D_SERCOM0_PAD0
#define CONF_TX_USART_PINMUX_PAD1  PINMUX_PA05D_SERCOM0_PAD1
#define CONF_TX_USART_PINMUX_PAD2  PINMUX_PA06D_SERCOM0_PAD2
#define CONF_TX_USART_PINMUX_PAD3  PINMUX_PA07D_SERCOM0_PAD3



#endif /* SME_UART_H_ */